apm-server:
  host: "0.0.0.0:8200"
  secret_token: ""

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"

logging.level: info

monitoring:
  enabled: true
  elasticsearch:
    username: "elastic" 
    password: "changeme"

queue.mem:
  events: 4096
  flush.min_events: 1000
  flush.timeout: 1s
