apm:
  service_name: quant_trading
  server_url: http://apm-server:8200
  environment: production

profiling:
  enabled: true
  sample_rate: 0.1

tracing:
  enabled: true
  exporter: jaeger

metrics:
  prometheus:
    enabled: true
    path: /metrics
    port: 9090
