
backtest:
    start_date: "2023-01-01"
    end_date: "2023-12-31"
    initial_capital: 100000
    commission: 0.0003

strategy:
    ma_cross:
        short_window: 5
        long_window: 20
        risk_limit: 0.02

risk_management:
    max_position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.05
